// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGgidoBRJGa6LXGyfHBu8LCsxr17glmuk',
    appId: '1:315063476023:web:0974b55b0867f7ed6c84b2',
    messagingSenderId: '315063476023',
    projectId: 'collectors-catalog-3ec8c',
    authDomain: 'collectors-catalog-3ec8c.firebaseapp.com',
    storageBucket: 'collectors-catalog-3ec8c.firebasestorage.app',
    measurementId: 'G-Y6LRYRDJG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASMIU1Buq9ZczuXibhL0towX5m57A_Kwg',
    appId: '1:315063476023:android:a631c66ff73bbf5b6c84b2',
    messagingSenderId: '315063476023',
    projectId: 'collectors-catalog-3ec8c',
    storageBucket: 'collectors-catalog-3ec8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbYWrmFap6ZHSFSK82lLnmxPSXsXp_8Fc',
    appId: '1:315063476023:ios:a97967427b19aa426c84b2',
    messagingSenderId: '315063476023',
    projectId: 'collectors-catalog-3ec8c',
    storageBucket: 'collectors-catalog-3ec8c.firebasestorage.app',
    iosBundleId: 'com.example.collectorsCatalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbYWrmFap6ZHSFSK82lLnmxPSXsXp_8Fc',
    appId: '1:315063476023:ios:a97967427b19aa426c84b2',
    messagingSenderId: '315063476023',
    projectId: 'collectors-catalog-3ec8c',
    storageBucket: 'collectors-catalog-3ec8c.firebasestorage.app',
    iosBundleId: 'com.example.collectorsCatalog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGgidoBRJGa6LXGyfHBu8LCsxr17glmuk',
    appId: '1:315063476023:web:330c68339e86c8876c84b2',
    messagingSenderId: '315063476023',
    projectId: 'collectors-catalog-3ec8c',
    authDomain: 'collectors-catalog-3ec8c.firebaseapp.com',
    storageBucket: 'collectors-catalog-3ec8c.firebasestorage.app',
    measurementId: 'G-VT4PS4NNVN',
  );
}
